<style>

.cloud { padding: 2px; line-height: 2em; text-align: center; }
.cloud a { padding: 3px; }

.cloud {
    background:#F5F5F5 none repeat scroll 0 0;
    border:3px solid #EEEEEE;
    margin:3em auto;
    width:50%;
}

.tag {
    font-family: Tahoma;
    /*padding: 4px 4px 4px 4px;*/
    letter-spacing: 2px;
    text-decoration: none;
}

.cloud a:hover {
	color: #fff;
	background: #005599;
}

span.size1 a {
    color: #000;
    font-size: 180%;
}
span.size2 a{
    color: #333;
    font-size:160%;
}
span.size3 a{
    color: #666;
    font-size: 140%;
}
span.size4 a{
    color: #999;
    font-size: 120%;
}
span.size5 a{
    color: #aaa;
    font-size: 100%;
}
span.size6 a{
    color: #bbb;
    font-size: 90%;
}
span.size7 a {
    color: #ccc;
    font-size: 80%;
}
span.size8 a{
    color: #ddd;
    font-size: 70%;
}
span.size0 a{
    color: #ccc;
    font-size: 60%;
}
</style>

<?php View::content(); ?>

<h3>Cloud Tags</h3>

<?
Load::lib('Cloud');
$cloud = new wordCloud();
foreach ($tags as $tag) {
	$cloud->addWord($tag['name'], $tag['count']);
}
View::helpers('TagCloud');
$tagCloud = new TagCloud($tags);
?>
<div class='cloud'><?php echo $cloud->showCloud(); ?></div>