<?php View::content() ?>
<div class="posts">
<?php if(isset($b)): ?>
	<h2>Resultado de búsqueda por "<?php echo $b ?>"</h2>
	<?php foreach ($result as $post): ?>
	<h2><?php echo Html::link("noticias/$post->url_title/", $post->title, "title= \"$post->title\"")  ?></h2>
	<p class='info'>
        Enviado por <?php echo $post->author; ?> el <?php echo strftime("%e de %B del %Y", strtotime($post->creation_at));  ?>
    </p>
    <?php endforeach; ?>
<?php else: ?>
	<h2>No haz colocado nada en el campo de búsqueda!</h2>
<?php endif;?>
</div>
