<div id="comments">

<h3>Dejanos tu Comentario</h3>

<div class="form">
    <?php //echo form_tag("comment/create/$postSlug/") ?>
    <?php echo form_tag("newComment/$postSlug/") ?>
        <div class="row">
            <label for="comment_author">Nombre</label>
            <?php echo text_field_tag(array('comment.author', 'size'=>'50')) ?>
        </div>
        <div class="row">
            <label for="comment_email">Correo</label>
            <?php echo text_field_tag(array('comment.email', 'size'=>'50')) ?>
            <p class="hint">Su dirección de correo no será publicada.</p>
        </div>
        
        <div class="row">
            <label for="comment_url">Sitio Web</label>
            <?php echo text_field_tag(array('comment.url', 'size'=>'50')) ?>
            <p class="hint">Recuerda colocar http://</p>
        </div>
        
        <div class="row">
            <label for="comment_content">Comentario</label>
            <?php echo textarea_tag('comment.content', 'cols: 57', 'rows: 6') ?>
        </div>
        
        <div class="row">
            <label for="captcha">Código Verificación</label>
            <img src="<?php echo URL_PATH . 'captcha/0' ?>" id="captcha" alt="CAPTCHA Image" />
            <div><a href="#" onclick="document.getElementById('captcha').src = '<?php echo URL_PATH ?>captcha/securimage/' + Math.random(); return false">Nueva Imagen</a></div>
            <?php echo text_field_tag(array('captcha_code')) ?>
        </div>
        
        <div class="row action">
            <?php echo hidden_field_tag(array('comment.post_id', 'value'=>$postID)) ?>
            <?php echo submit_tag('Enviar') ?>
        </div>
    <?php echo end_form_tag() ?>
</div>
</div>