<?php Load::lib('Utils')?>
<div class="posts">
	<h2>Últimas Noticias</h2>
	<?php foreach ($lastPost as $post): ?>
	<h2><?php echo Html::link("noticias/$post->url_title/", $post->title, "title= \"$post->title\"")  ?></h2>
	<p class='info'>
        Enviado por <?php echo $post->author; ?> el <?php echo strftime("%e de %B del %Y", strtotime($post->creation_at));  ?>
    </p>
    <p><?php echo Utils::truncateWord($post->entry)?></p>
    <?php endforeach; ?>
</div>
