<h3>Nueva Noticia</h3>
<div class="form">
    <?php View::content(); ?>
    <?php echo form_tag('admin/post/create/') ?>
        <div class="row">
            <label for="post_title">Titulo</label>
            <?php echo text_field_tag(array('post.title', 'size'=>'40')) ?>
        </div>

        <div class="row">
            <label for="post_entry">Entrada</label>
            <?php echo textarea_tag('post.entry', "style: width:100%")?>
        </div>

        <div class="row">
            <label for="post_status">Estado</label>
            <?php echo select_tag('post.status',
                       array('0' => 'Borrador', '1' => 'Publicado', '2' => 'Archivado'), 'include_blank: Seleccione uno...') ?>
        </div>

        <div class="row">
            <label for="post_author">Autor</label>
            <?php echo text_field_tag(array('post.author', 'size'=>'40')) ?>
        </div>

        <div class="row">
            <label for="tags">Etiquetas</label>
            <?php echo text_field_tag(array('tags', 'size'=>'100', 'value'=>'Default')) ?>
        </div>

        <div class="row action">
            <?php View::partial('widgets/tinymce') ?>
            <?php echo submit_tag('Enviar') ?>
        </div>
    <?php echo end_form_tag() ?>
</div>
<?php echo Tag::js('jquery/jquery.tag.editor'); ?>
<script type="text/javascript">
    $(document).ready(function() {
        $("#tags").tagEditor(
        {
            confirmRemoval: true,
			separator: ',',
			completeOnSeparator: true,
			completeOnBlur: true
        });
    });
</script>
