<h3>Editar Noticia</h3>
<div class="form">
    <?php View::content(); ?>
    <?php echo Form::open("admin/post/edit/$post->id/") ?>
        <div class="row">
            <label for="post_title">Titulo</label>
            <?php echo Form::text('post.title', "size='40'") ?>
        </div>

        <div class="row">
            <label for="post_entry">Entrada</label>
            <?php echo Form::textarea('post.entry', "style='width:100%'")?>
        </div>

        <div class="row">
            <label for="post_status">Estado</label>
            <?php echo Form::select('post.status',
                       array('0' => 'Borrador', '1' => 'Publicado', '2' => 'Archivado')) ?>
        </div>

        <div class="row">
            <label for="post_author">Autor</label>
            <?php echo Form::text('post.author', "size='40'") ?>
        </div>

        <div class="row">
            <label for="tags">Etiquetas</label>
            <?php
                $value = array();
                foreach ($tags as $tag) {
                	$value[] = $tag->name;
                }
                $value = implode(',', $value);
            ?>
            <?php echo Form::text('tags', "size='100'", $value) ?>
        </div>

        <div class="row action">
            <?php echo Form::hidden('post.id') ?>
            <?php echo Form::hidden('post.slug') ?>
            <?php echo Form::hidden('post.creation_at') ?>
            <?php View::partial('widgets/tinymce') ?>
            <?php echo Form::submit('Enviar') ?>
        </div>
    <?php echo Form::close() ?>
</div>
<?php echo Tag::js('jquery/jquery.tag.editor'); ?>
<script type="text/javascript">
    $(function() {
        $("#tags").tagEditor(
        {
            confirmRemoval: true,
			separator: ',',
			completeOnSeparator: true,
			completeOnBlur: true,
			url: '<?php echo PUBLIC_PATH ?>admin/post/delTag/<? echo $post->id ?>/'
        });
    });
</script>
