<?php View::content(); ?>
<?php echo Form::open() ?>
<table>
    <tr>
        <td>Perfil</td>
        <td>
            <?php echo Form::dbSelect('usuario.perfil_id', $perfiles, 'nombre', '- seleccione -') ?>
        </td>
    </tr>
    <tr>
        <td>Login</td>
        <td><?php echo Form::text('usuario.login') ?></td>
    </tr>
    <tr>
        <td>Nombre</td>
        <td><?php echo Form::text('usuario.nombre') ?></td>
    </tr>
    <tr>
        <td>Correo</td>
        <td><?php echo Form::text('usuario.mail') ?></td>
    </tr>
    <tr>
        <td>Clave</td>
        <td><?php echo Form::pass('usuario.password') ?></td>
    </tr>
    <tr>
        <td>Confirma Clave</td>
        <td><?php echo Form::pass('usuario.password2') ?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <?php echo Form::hidden('usuario.status', null, 'A') ?>
            <td><?php echo Form::submit('Agregar') ?></td>
        </tr>
    </table>
<?php echo Form::close() ?>