<div class="content">
    <?php echo View::content(); ?>
    <h3>Usuarios</h3>
    <ul>
    <?php foreach ($listUsuarios->items as $item) : ?>
    <li>
        <strong><?php echo $item->login ?></strong>
        <a href="#">Editar</a>
        <?php echo Html::link("usuarios/del/$item->id/", 'Borrar') ?>
        <a href="#" title='Nombre del Grupo'><?php echo $item->getPerfil()->nombre ?></a>        
    </li>
    <?php endforeach; ?>
    </ul>
    
    <?php if($listUsuarios->prev) echo Html::link("admin/usuarios/index/$listUsuarios->prev/", '<< Anterior |'); ?>
    <?php if($listUsuarios->next) echo Html::link("admin/usuarios/index/$listUsuarios->next/", 'Próximo >>'); ?>
</div>