<?php View::content(); ?>
<?php echo form_tag('usuarios/create') ?>
<table>
    <tr>
        <td>Perfil</td>
        <td><?php echo select_tag(array('usuarios.perfiles_id',
                                        $perfiles, 'option'=>'nombre',
                                        'include_blank' => 'Seleccione...')) ?>
        </td>
    </tr>
    <tr>
        <td>Login</td>
        <td><?php echo text_field_tag(array('usuarios.login')) ?></td>
    </tr>
    <tr>
        <td>Correo</td>
        <td><?php echo text_field_tag(array('usuarios.mail')) ?></td>
    </tr>
    <tr>
        <td>Clave</td>
        <td><?php echo password_field_tag(array('usuarios.password')) ?></td>
    </tr>
    <tr>
        <td>Confirma Clave</td>
        <td><?php echo password_field_tag(array('usuarios.password2')) ?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <?php echo hidden_field_tag(array('usuarios.status', 'value'=>'A')) ?>
        <td><?php echo submit_tag('Agregar') ?></td>
    </tr>
</table>
<?php echo end_form_tag() ?>