<div class="content">
    <?php echo View::content(); ?>
    <h3>Usuarios</h3>
    <ul>
    <?php foreach ($listUsuarios->items as $item) : ?>
    <li>
        <a href="#">Edit</a>
        <?php echo link_to(array("usuarios/del/$item->id/", 'Borrar')) ?>
        <a href="#" title='Nombre del Grupo'><?php echo $item->Perfiles()->nombre ?></a>
        <strong><?php echo $item->login ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
    
    <?php if($listUsuarios->prev) echo link_to(array("admin/usuarios/index/$listUsuarios->prev/", '<< Anterior |')); ?>
    <?php if($listUsuarios->next) echo link_to(array("admin/usuarios/index/$listUsuarios->next/", 'Próximo >>')); ?>
</div>