<h3>Nuevo Menu</h3>
<div class='form'>
    <?php echo Form::open('admin/menus/create/') ?>
    <?php View::content(); ?>
        <div class="row">
           <label>Nombre</label>
           <?php echo Form::text('menus.nombre') ?>
        </div>
        <div class="row">
           <label>Titulo</label>
           <?php echo Form::text('menus.titulo') ?>
        </div>
        <div class="row action"> 
            <?php echo Form::submit('Agregar') ?>
        </div>
    <?php echo Form::close(); ?>
</div>