<h3>Nueva Categoria</h3>
<div class="form">
    <?php View::content(); ?>
    <?php echo Form::open('admin/categoria/create/') ?>
    <?php echo Form::hidden('categoria.usuario_id',"size='40'", "$usuario_id") ?>
    <div class="row">
        <label for="categoria_nombre">Nombre</label>
        <?php echo Form::text('categoria.nombre', "size='40'") ?>
    </div>
    
    <div class="row action">
        <?php View::partial('widgets/tinymce') ?>
        <?php echo Form::submit('Enviar') ?>
    </div>
    <?php echo Form::close() ?>
</div>
<?php echo Tag::js('jquery/jquery.tag.editor'); ?>
<script type="text/javascript">
    $(function() {
        $("#tags").tagEditor(
        {
            confirmRemoval: true,
            separator: ',',
            completeOnSeparator: true,
            completeOnBlur: true
        });
    });
</script>