<h3>Editar Categoría</h3>
<div class="form">
    <?php View::content(); ?>
    <?php echo Form::open("admin/categoria/edit/$categoria->id/") ?>
    <?php echo Form::hidden('categoria.id', null, $categoria->id) ?>
    <div class="row">
        <label for="categoria_title">Nombre</label>
        <?php echo Form::text('categoria.nombre', "size='40'") ?>
    </div>
    <div class="row">
        <label for="categoria_url">URL</label>
        <?php echo Form::text('categoria.url', "size='40'") ?>
    </div>
    <div class="row">
        <label for="categoria_estado">Estado</label>
        <?php echo Form::select('categoria.estado',
                array('1' => 'Activa', '0' => 'Inactiva')) ?>
    </div>
    <div class="row action">
        <?php echo Form::submit('Enviar') ?>
    </div>
    <?php echo Form::close() ?>
</div>