<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=utf-8' />
    <title><?php echo $pageTitle; ?></title>
    <?php echo Tag::js('jquery/jquery-1.3.2.min') ?>
    <?php echo Tag::css('bienvenida'); ?>
    <?php echo Tag::css('style'); ?>
    <?php //echo Tag::includeCss() ?>
    <?php echo Tag::includeLinks();?>
</head>
<body>
	<?php //View::partial('debug') ?>
    <?php View::partial('head') ?>
    <?php View::partial('menu2'); ?>
    <?php View::content() ?>
    <?php View::partial('kumbia/footer') ?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp'); ?>
</body>
</html>
