<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>[Administración] - <?php echo $pageTitle ?></title>
<?php echo Tag::css('login/screen'); ?>
<?php echo Tag::includeLinks();?>
</head>
<body>
<div id="cont">
  <div class="box lock"> </div>
  <div id="loginform" class="box form">
    <h2>Ingrese sus Credenciales <a href="" class="close">Close it</a></h2>
    <div class="formcont">
      <fieldset id="signin_menu">
      <span class="message" style="color: red"><?php echo $error_msj ?></span>
		<form method="post" id="signin">
        <label for="username">Usuario</label>
        <input id="txt_login" name="txt_login" value="" title="username" class="required" tabindex="1" type="text">
        </p>
        <p>
          <label for="password">Clave</label>
          <input id="txt_password" name="txt_password" value="" title="password" class="required" tabindex="2" type="password">
        </p>
        <p class="clear"></p>
       <a href="#" class="forgot">Recordar?</a>
        <p class="remember">
          <input id="signin_submit" value="Entrar" tabindex="3" type="submit">
          <input id="cancel_submit" value="Cancelar" tabindex="4" type="button">
          <input type="hidden" name='mode' value='auth_login' />
        </p>
      </form>
      </fieldset>
    </div>
    <div class="formfooter"></div>
  </div>
</div>

<?php echo javascript_include_tag('jquery/jquery-1.3.2.min') ?>
<!-- <script type='text/javascript' src='http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js?ver=1.3.2'></script> -->
<script type="text/javascript">
            $(document).mouseup(function() {
                $("#loginform").mouseup(function() {
                    return false
                });

                $("a.close").click(function(e){
                    e.preventDefault();
                    $("#loginform").hide();
                    $(".lock").fadeIn();
                });

                if ($("#loginform").is(":hidden"))
                {
                    $(".lock").fadeOut();
                } else {
                    $(".lock").fadeIn();
                }
                $("#loginform").toggle();
            });


            // I dont want this form be submitted
            $("form#signin").submit(function() {
              return true;
            });

            // This is example of other button
            $("input#cancel_submit").click(function(e) {
                    $("#loginform").hide();
                    $(".lock").fadeIn();
            });
</script>

</body>
</html>
