<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo $pageTitle; ?></title>
    <?php echo stylesheet_link_tag('main') ?>
    <?php echo stylesheet_link_tag('template-main') ?>
    <?php echo stylesheet_link_tags(); ?>
</head><body>


<div id="header" class="fluid">
	<div class="container">
	  <h1><a href="/">CaChi</a></h1>
	</div>
</div>

<div id="content" class="fluid">
	<div class="container">
		<div style="float: left; width: 602px; margin-right: 40px;">
			<?php View::content(); ?>
		</div>
		<div style="float: left; width: 300px; padding-left: 10px; border-left: solid 1px #eee">
		<h2>Side Column</h2>
			<?php 
			//View::partial('widgets/flickr_rss_lightbox', false, 'name: Flikr');
			//View::partial('widgets/flickr_rss22', false, 'url: http://api.flickr.com/services/feeds/photos_public.gne?tags=kumbiaphp&lang=es-us&format=rss_200, name: XXX') ?>
		</div>
	</div>
</div>

<div id="features" class="fluid">
	<div class="container">
		<div class="widget">
		      <h2>KumbiaPHP</h2>
		      <ul>
                <li><a title="Después de unos meses de arduo trabajo el Nuevo Equipo de Desarrollo de KumbiaPHP Framework se enorgullece en anunciar el Beta 1 de la versión 1.0 codename Spirit, esta versión su enfoque principal estuvo en un refactor del core del framework, una reescritura completa de manera de tener un core muy consistente y mantenible, esto [...]" href="http://www.kumbiaphp.com/blog/2009/08/14/kumbiaphp_framework_1_0_beta1_liberada/">KumbiaPHP Framework 1.0 Beta 1 Liberada!</a></li>
                <li><a title="Este post nace luego de una conversación en el IRC de KumbiaPHP dado por una duda de unos de nuestro usuarios ya que deseaba realizar una consulta SQL, lo cierto del caso es que dicha consulta “pensaba” desde el controller siento esto totalmente incorrecto, ya que no respeta el MVC y en este sentido se [...]" href="http://www.kumbiaphp.com/blog/2009/08/07/como_usar_los_modelos_en_kumbiaphp/">Como usar los Modelos en KumbiaPHP</a></li>
                <li><a title="Como saben algunos desde hace tiempo KumbiaPHP como proyecto esta registrado en ohloh.net/KumbiaPHP,  el cual valora el trabajo que hacemos en el proyecto, en este sentido es de suma importancia poder contar con el apoyo de la comunidad (ustedes) pinchando el botón el que se muestra:
 Una vez que hayas votado coloca en tu perfil [...]" href="http://www.kumbiaphp.com/blog/2009/07/24/apoya_a_kumbiaphp_en_ohlohnet/">Apoya a KumbiaPHP en ohloh.net</a></li>
                <li><a title="Les comunicamos que  KumbiaPHP ya esta en Twitter.
Donde nos podran seguir de forma rápida, los avances del proyecto de forma más continuada que en el blog.
Les invitamos a que sean seguidores (followers) y sigan nuestros cambios en la vida del proyecto por esta vía.
Este es otro mecanismo para estar más cerca de la comunidad.
Aqui teneis [...]" href="http://www.kumbiaphp.com/blog/2009/07/09/kumbia-php-framework-en-twitter/">Kumbia PHP Framework en Twitter</a></li>
                <li><a title="El Equipo de Desarrollo de KumbiaPHP se complace en anunciar de forma oficial la Nueva Estructura de Directorio del Framework, esto luego de hacer varias pruebas en ambientes de producción y todas fueron superadas sin mayor problema.
En el siguiente paper hemos resaltado de forma sintetizada las bondades que ofrece este nuevo cambio incorporado.
Estructura de Directorio [...]" href="http://www.kumbiaphp.com/blog/2009/06/01/kumbiaphp_nueva_estructura_del_framework/">KumbiaPHP 1.0 nueva estructura del framework</a></li>
                <li><a title="En el Equipo de Desarrollo de KumbiaPHP Framework nos hemos dedicado a darle un cambio radical al framework, no sólo en velocidad (Benchmark) y core de KumbiaPHP en varios aspectos, sino también en la Pantalla Bienvenida una vez instalado el framework. Algo sumamente importante al momento de realizar cualquier instalación, siempre lo primero que vemos [...]" href="http://www.kumbiaphp.com/blog/2009/05/31/spirit_estrena_nueva_bienvenida/">Spirit estrena nueva bienvenida</a></li>
                <li><a title="Tal como dice el título en este post solo se dará algunos de los avances que hemos alcanzado estos días que han estado cargado de trabajo en las nuevas implementaciones de kumbiaphp web &amp; app framework. En este sentido no entraremos en detalle porque hemos pensado tener un post dedicado exclusivamente explicando a profundidad los [...]" href="http://www.kumbiaphp.com/blog/2009/04/30/avances_de_kumbiaphp_framework/">Avances de kumbiaphp framework</a></li>
                <li><a title="Desde hace más de un año kumbiaphp framework tiene un canal de IRC, pero no fue hasta hace un par de días que fue registrado oficialmente en IRC-Hispano, esto se traduce en que ahora el canal irc cuenta con Operator algo útil para administrar el canal.
Como dato adicional nos hemos dado cuenta que aparte de [...]" href="http://www.kumbiaphp.com/blog/2009/04/24/kumbiaphp_irc_registrado/">KumbiaPHP: IRC Registrado</a></li>
                <li><a title="Comenzamos a publicar una serie de Benchmark que hemos realizado a la versión 1.0 Spirit pre beta vs (Symfony, Zend y Cake) la intención es mostrar los avances que hemos obtenido con la última versión (Spirit) de kumbiaphp framework.
Seguimos trabajando para mejorar más la velocidad antes de la versión final. Además de velocidad, se han [...]" href="http://www.kumbiaphp.com/blog/2009/03/27/benchmark_frameworks_kumbiaphp_vs_symfony_zend_cakephp/">Benchmark Frameworks KumbiaPHP vs (Symfony, Zend y CakePHP)</a></li>
                <li><a title="Me imagino que muchos se han hecho la pregunta ¿Porqué se llama Spirit la versión 1.0 de kumbiaphp framework? y si no se la han hecho, en este post se pretende aclarar que nos llevo a tomar la determinación de colocar como code name Spirit.

Spirit, es el primero de los dos robots que forman parte [...]" href="http://www.kumbiaphp.com/blog/2009/03/11/porque-se-llama-spirit/">Porqué se llama Spirit?</a></li>
            </ul>
			<?php //View::partial('widgets/feed', false, 'url: http://www.kumbiaphp.com/blog/feed/, name: KumbiaPHP') ?>
		</div>
		<div class="widget">
			<h2>Column 2</h2>
			<p>Tamen
meus feugait vel dolore nonummy quibus consequat esse tincidunt, sed ea
quidne luctus, bene. Singularis luctus jugis feugait exerci eros huic
facilisis letalis luptatum. <?php //View::partial('widgets/flickr_rss_lightbox', false, 'name: Flikr') ?></p>
		</div>
		<div class="widget">
			<h2>Column 3</h2>
			<p>Tamen
meus feugait vel dolore nonummy quibus consequat esse tincidunt, sed ea
quidne luctus, bene. Singularis luctus jugis feugait exerci eros huic
facilisis letalis luptatum. </p>
		</div>
	</div>
</div>
<div id="footer" class="fluid">
	<div class="container">
	   <?php //echo porwer_by_kumbiaphp() ?>
		</p>
	</div>
</div>

</body></html>