<div class="content">
    <?php echo View::content(); ?>
    <h3>Perfiles</h3>
    <ul>
    <?php foreach ($listPerfiles->items as $item) : ?>
    <li>
        <?php echo Html::link("perfil/del/$item->id/", 'Borrar') ?>
        <strong><?php echo $item->nombre ?></strong>
    </li>
    <?php endforeach; ?>
    </ul>
    
    <?php if($listPerfiles->prev) echo Html::link("perfil/index/$listUsuarios->prev/", '<< Anterior |'); ?>
    <?php if($listPerfiles->next) echo Html::link("perfil/index/$listUsuarios->next/", 'Próximo >>'); ?>
</div>