
<?php if($counComment>=1): ?>
<h3>
  <?php echo $counComment>1 ? $counComment . ' Comentarios' : 'Un Comentario'; ?>
</h3>
<?php endif; ?>

<?php foreach($comments as $comment): ?>
<div class="comment" id="c<?php echo $comment->id; ?>">
  <div class="author"><a href='<?php echo $comment->url ?>' target="_blank"><?php echo $comment->author ?></a> dice:</div>
  
  <div class="time">
    <?php echo strftime("%e de %B del %Y, a las %R", strtotime($comment->created_at)); ?>
  </div>
  <div class="content"><?php echo $comment->content; ?></div>
</div>
<?php endforeach; ?>
