<script type="text/javascript">
    var headID = document.getElementsByTagName("head")[0];
    var cssNode = document.createElement('link');
    cssNode.type = 'text/css';
    cssNode.rel = 'stylesheet';
    cssNode.href = '<?php echo PUBLIC_PATH ?>css/menu/dropdown.css';
    cssNode.media = 'all';
    headID.appendChild(cssNode);

    var cssNode = document.createElement('link');
    cssNode.type = 'text/css';
    cssNode.rel = 'stylesheet';
    cssNode.href = "<?php echo PUBLIC_PATH ?>css/menu/default.advanced.css";
    cssNode.media = 'all';
    headID.appendChild(cssNode);
</script>

<ul class="dropdown dropdown-horizontal">
    <?php foreach(Load::model('controllers')->getMenu(Auth::get('perfiles_id')) as $item): ?>
        <li>
            <a href='#' title="<?php echo $item->Menus()->titulo ?>"><?php echo $item->Menus()->nombre ?></a>
            <ul>
            <?php foreach (Load::model('controllers')->getSubMenu(Auth::get('perfiles_id'), $item->Menus()->id) as $controlador): ?>
                <?php if($controlador->url == 'null'){?>
                    <li class="empty"><?php echo $controlador->nombre ?></li>
                <?php }else{?>
                    <li><?php echo Html::link("$controlador->url/", $controlador->nombre) ?></li>
                <?php }?>
            <?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
    <li>
        <a title="Menu Administrativo" href="#">Admin</a>
        <ul>
            <li class="empty">Controladores</li>
            <li><?php echo Html::link('admin/controllers/','Listar Controladores') ?></li>
            <li><?php echo Html::link('admin/controllers/create/', 'Nuevo Controlados') ?></li>
            <li class="empty">Menus</li>
            <li><?php echo Html::link('admin/menus/', 'Listar Menu') ?></li>
            <li><?php echo Html::link('admin/menus/create/', 'Nuevo Menu') ?></li>
        </ul>
    </li>
    <li class="right">
        <a>Salir</a>
    </li>
</ul>
