<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License

Name       : Proofing 
Description: A two-column, fixed-width design for 1024x768 screen resolutions.
Version    : 1.0
Released   : 20100216

-->
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <title><?php echo $pageTitle ?></title>
        <meta name="keywords" content="" />
        <meta name="description" content="" />
        <link rel="shortcut icon" href="http://blog.simacel.com/img/favicon.ico" type="image/x-icon" />
        <?php Tag::css('proofing/style') ?>
        <?php echo Html::includeCss() ?>
    </head>
    <body>
        <div id="header-wrapper">
            <div id="header">
                <div id="menu">
                    <ul>
                        <li><a href="/" accesskey="1">Inicio</a></li>
                        <li><?php echo Html::link('acerca/', 'Acerca', 'accesskey="2"'); ?></li>
                        <li><?php echo Html::link('contacto/', 'Contacto', 'accesskey="3"'); ?></li>
                    </ul>
                </div>
                <!-- end #menu -->
                <div id="search">
                    <form method="get" action="">
                        <fieldset>
                            <input type="text" name="s" id="search-text" size="15" />
                            <input type="submit" id="search-submit" value="GO" />
                        </fieldset>
                    </form>
                </div>
                <!-- end #search -->
            </div>
        </div>
        <!-- end #header -->
        <!-- end #header-wrapper -->
        <div id="logo">
            <div style="float: left; margin-right: 10px;"><a href="/"><?php echo Html::img('simacel.png','simacel')?></a></div>
            <h1><a href="/">blog.simacel.com</a></h1>
            <p><em>La información en tus manos</em></p>
        </div>
        <hr />
        <!-- end #logo -->
        <div id="page">
            <div id="page-bgtop">
                <div id="content">
                    <?php View::content(); ?>
                </div>
                <!-- end #content -->
                <div id="sidebar">
                    <?php View::partial('twitter/siguenos') ?>

                    <?php View::partial('noticias/recientes') ?>                    

                    <?php View::partial('twitter/busqueda') ?>

                    <?php View::partial('cloud_tag') ?>
                </div>
                <!-- end #sidebar -->
                <div style="clear: both;">&nbsp;</div>
            </div>
            <!-- end #page -->
            <div id="footer">
                <p>Copyright (c) 2010 simacel.com. Todos los derechos reservados<br />
                Potenciado por <a href="http://www.kumbiaphp.com" title="KumbiaPHP Framework">KumbiaPHP Framework</a></p>
            </div>
            <!-- end #footer -->
        </div>
        <div style="text-align: center; font-size: 0.75em;">Design downloaded from <a href="http://www.freewebtemplates.com/">free website templates</a>.</div>
        <?php View::partial('analytics') ?>

        <!--<?php echo 'Tiempo: '.round((microtime(1)-START_TIME),4).' seg.'; echo ', Memoria Usada: '.number_format(memory_get_usage() / 1048576, 2).' MB';?>-->
    </body>
</html>