<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <title><?php echo $pageTitle ?></title>
    <link media="screen" type="text/css" rel="stylesheet" href="/css/theme/style.css">
</head>

<body>
<?php //View::partial('debug') ?>
<div id="wrapper">
	<div id="header">
		<div id="logo"><h1><?php echo Html::link('', 'CaChi Blog, El Blog de Deivinson Tejeda', 'accesskey="1" title="CaChi Blog, El Blog de Deivinson Tejeda"'); ?></h1>
		</div>

		<div id="topsearch">
	    <form action="/post/busqueda" method='get' 'id="searchform">
			<input type="text" class="swap_value" id="s" name="b" value="" />
			<input type="image" title="Search" alt="Search" id="go" src="/css/theme/images/go.gif" />
		<?php echo Form::close() ?>
		</div>
		<div class="clear"/>
	</div>

	<div id="nav">
		<ul>
    		<li class="current_page_item"><?php echo Html::link('', 'PORTADA', 'accesskey="1"'); ?></li>
    		<li><?php echo Html::link('about/', '¿SOBRE MÍ?', 'accesskey="2"'); ?></li>
    		<li><?php echo Html::link('articulo/archivos/', 'RECIENTES', 'accesskey="3"'); ?></li>
    		<li><?php echo Html::link('about/', '¿TEMIGA?', 'accesskey="4"'); ?></li>
		</ul>
	</div>

	<div id="main">

	<div id="content">
		<?php View::content(); ?>
	</div><!-- Content -->

    <div id="sidebar">

    <div class="boxes">
    	<h2>Sobre este Blog</h2>
    	<p>Esto pretende ser un espacio para compartir ideas y conocimientos sobre diferentes topicos de interes</p>
    </div>

    <div class="boxes">
        <h2>Subscribe</h2>
        <?php echo Html::link('articulo/rss/', 'Suscribete RSS', 'class="rss"') ?>
    </div>

    <div class="boxes">
        <?php //View::partial('cloud_tag') ?>
    </div>
    <div class="boxes">
        <?php //View::partial('widgets/twitter') ?>
    </div>
    <div class="boxes">
		<?php View::partial('noticias/recientes', '+1 week') ?>
    </div>

    <div id="lsidebar">
    	<?php View::partial('widgets/enlaces', '+1 year') ?>
    </div>
    <div class="clear"></div>
    </div>
<div class="clear"></div>
</div>
    <div id="footer">
    	<p style="float:left;">Powered by <a href='http://www.kumbiaphp.com/' title='Hecho con KumbiaPHP Framework'>KumbiaPHP Framework</a></p>
        <p style="float:right;">
            <a href="http://jigsaw.w3.org/css-validator/"><img src="/img/css.gif" alt="Valid CSS!" /></a>
            <a href="http://validator.w3.org/check?uri=referer"><img src="/img/xhtml.gif" alt="Valid XHTML 1.0 Transitional" /></a>
        </p>
        <br clear="all" />
    </div>
</div>
<!-- <p><?php echo 'Tiempo: '.round((microtime(1)-START_TIME),4).' seg.'; echo ', Memoria Usada: '.number_format(memory_get_usage() / 1048576, 2).' MB';?></p> -->
</body>
</html>
