<div id='posts'>
    <h2>¿Qué es SIMACEL?</h2>

    <div style="float: left; margin: 10px;">        
            <?php echo Html::img('logo-simacel-medium.png','Logo de Simacel')?>
    </div>
    <p>
        <strong>SIMACEL</strong> es una comunidad que gira en torno a los medios
        alternativos para entregar la información en las manos de los usuarios.
        Lider en el <strong>envío masivo de mensajes de texto</strong> para promoción de
        diferentes productos y principalmente eventos en diferentes 
        ciudades colombianas. Manejo de <strong>Mail Marketing</strong> atacando el internet
        de forma responsable, las redes sociales y 
        el portal <a href="http://www.simacel.com">www.simacel.com</a> el cual se encargará de
        manejar notas de sucesos a nivel nacional y ampliar 
        información de eventos y campañas que se realizan por otros medios.
    </p>
    <p>
        En la actualidad SIMACEL esta posicionandose como una de las mejores
        alternativas para estar informado de lo que pasa a nivel nacional,
        regional y local en cada una de las ciudades en las que está presente.
        Los usuarios de SIMACEL pueden recibir en cada promoción diferentes
        beneficos como descuentos, entradas privilegiadas e información exclusiva.
    </p>
    <p>
        Nuestro equipo de trabajo está conformado por personas emprendedoras
        con gran conocimiento en cada una de sus areas,
        reconocidos periodistas, fotografos y diseñadores que en esta nueva etapa
        del portal de internet <a href="http://www.simacel.com">www.simacel.com</a>
        y <strong>SIMACEL La Revista</strong> están trabajando arduamente para ofrecerles lo mejor.
    </p>
    <p>
        <strong>SIMACEL, la informacion en tus manos.</strong>
    </p>
</div>