<h2>Contacto</h2>
<?php View::content() ?>
<div class="form">
    <?php echo Form::open("contact/", 'post') ?>
    <table>
        <tr>
            <td><label for="contacto_autor">Nombre (*):</label></td>
            <td><?php echo Form::text('contacto.nombre')?></td>
        </tr>
        <tr>
            <td><label for="contacto_email">Correo (*):</label></td>
            <td><?php echo Form::text('contacto.correo')?></td>
        </tr>        
        <tr>
            <td><label for="contacto_autor">Comentario (*):</label></td>
            <td><?php echo Form::textarea('contacto.cuerpo',array('cols=65', 'rows=6'))?></td>
        </tr>
    </table>
    <p>
        <?php echo Form::submit('Enviar')?>
    </p>
    <?php echo Form::close() ?>
</div>
