<h3>Nueva Noticia</h3>
<div class="form">
    <?php View::content(); ?>
    <?php echo Form::open('admin/articulo/create/') ?>
    <?php echo Form::hidden('articulo.usuario_id', "size='40'", "$usuario_id") ?>
    <div class="row">
        <label for="articulo_titulo">Título</label>
        <?php echo Form::text('articulo.titulo', "size='40'") ?>
    </div>

    <div class="row">
        <label for="articulo_categoria">Categoría</label>
        <?php echo Form::dbSelect('articulo.categoria_id', $categorias, 'nombre', '- seleccione -') ?>
    </div>

    <div class="row">
        <label for="articulo_contenido">Contenido</label>
        <?php echo Form::textarea('articulo.contenido', "style='width:100%'") ?>
    </div>

    <div class="row">
        <label for="articulo_estado">Estado</label>
        <?php echo Form::select('articulo.estado',
                array('0' => 'Borrador', '1' => 'Publicado', '2' => 'Archivado')) ?>
    </div>

    <div class="row">
        <label for="tags">Etiquetas</label>
        <?php echo Form::text('tags', "size='100'", 'Default') ?>
    </div>

    <div class="row action">
        <?php View::partial('widgets/tinymce') ?>
        <?php echo Form::submit('Enviar') ?>
    </div>
    <?php echo Form::close() ?>
    </div>
<?php echo Tag::js('jquery/jquery.tag.editor'); ?>
<?php //echo Tag::js('jquery/ui/jquery-ui-1.8.1.custom'); ?>
<?php //echo Tag::js('elrte/elrte.min'); ?>
<?php //echo Tag::js('elrte/i18n/elrte.es'); ?>
<script type="text/javascript">
    $(function() {
        $("#tags").tagEditor(
        {
            confirmRemoval: true,
            separator: ',',
            completeOnSeparator: true,
            completeOnBlur: true
        });
        //Para el editor
        /*var opts = {
            lang         : 'es',   // set your language
            styleWithCss : true,
            height       : 400,
            toolbar      : 'complete'
        };
        // create editor
        $('#articulo_contenido').elrte(opts);*/
    });
</script>