<h3>Editar Noticia</h3>
<div class="form">
    <?php View::content(); ?>
    <?php echo Form::open("admin/articulo/edit/$articulo->id/") ?>
        <div class="row">
            <label for="articulo_title">Titulo</label>
            <?php echo Form::text('articulo.titulo', "size='40'") ?>
        </div>

        <div class="row">
            <label for="articulo_entry">Entrada</label>
            <?php echo Form::textarea('articulo.contenido', "style='width:100%'")?>
        </div>

        <div class="row">
            <label for="articulo_status">Estado</label>
            <?php echo Form::select('articulo.estado',
                       array('0' => 'Borrador', '1' => 'Publicado', '2' => 'Archivado')) ?>
        </div>

        <div class="row">
            <label for="tags">Etiquetas</label>
            <?php
                $value = array();
                foreach ($tags as $tag) {
                	$value[] = $tag->name;
                }
                $value = implode(',', $value);
            ?>
            <?php echo Form::text('tags', "size='100'", $value) ?>
        </div>

        <div class="row action">
            <?php echo Form::hidden('articulo.usuario_id') ?>
            <?php echo Form::hidden('articulo.id') ?>
            <?php echo Form::hidden('articulo.slug') ?>
            <?php echo Form::hidden('articulo.categoria_id') ?>
            <?php echo Form::hidden('articulo.creado_at') ?>
            <?php View::partial('widgets/tinymce') ?>
            <?php echo Form::submit('Enviar') ?>
        </div>
    <?php echo Form::close() ?>
</div>
<?php echo Tag::js('jquery/jquery.tag.editor'); ?>
<script type="text/javascript">
    $(function() {
        $("#tags").tagEditor(
        {
            confirmRemoval: true,
			separator: ',',
			completeOnSeparator: true,
			completeOnBlur: true,
			url: '<?php echo PUBLIC_PATH ?>admin/articulo/delTag/<? echo $articulo->id ?>/'
        });
    });
</script>
