<h3>Lista de artículos</h3>
<div class="content">
    <?php View::content(); ?>
    <table id="minimalist">
        <thead><tr>
                <th>Titulo</th>
                <th>Creado</th>
                <th>Publicado</th>
                <th>Autor</th>
                <th>Estado</th>                
                <th colspan="2" class='action'>Acciones</th>
            </tr></thead>
        <tbody>
            <? foreach($listPosts->items as $item):?>
            <tr>                
                <td><?php eh($item->titulo) ?></td>
                <td><?php eh($item->creado_at) ?></td>
                <td><?php eh($item->fecha_publicacion) ?></td>
                <td><?php eh($item->getUsuario()->nombre) ?></td>
                    <?php if($item->estado == Articulo::STATUS_PUBLISHED): ?>
                <td><img alt="Artículo Publicado" src="/img/admin/public.png" title="Artículo Publicado" /></td>
                    <?php else:?>
                <td><img alt="Candidato Artículo Bueno" src="/img/admin/candidato-articulo-bueno.png" title="Candidato Artículo Bueno" /></td>
                    <?php endif;?>
                <td><?php echo Html::link("admin/articulo/edit/$item->id/", Html::img('admin/edit.png'), "title='Editar Registro' class='edit'")?></td>
                <td><?php echo js::link("admin/articulo/del/$item->id/", '<img alt="Borrar" src="/img/admin/delete.png" title="Borrar Noticia" />', '¿Esta seguro que desea eliminar este registro?', 'del') ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php View::partial('paginators/classic', false, array('page' => $listPosts ,'url' => 'admin/articulo/index')); ?>
</div>
