<!-- Aquí su código para estadisticas -->
<!-- Start of StatCounter Code -->
<script type="text/javascript">
var sc_project=5839807;
var sc_invisible=1;
var sc_security="b31af318";
</script>

<script type="text/javascript"
src="http://www.statcounter.com/counter/counter_xhtml.js"></script><noscript><div
class="statcounter"><a title="tumblr tracker"
class="statcounter"
href="http://www.statcounter.com/tumblr/"><img
class="statcounter"
src="http://c.statcounter.com/5839807/0/b31af318/1/"
alt="tumblr tracker" /></a></div></noscript>
<!-- End of StatCounter Code -->
<!-- Google Analytics Code -->
<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try {
        var pageTracker = _gat._getTracker("UA-1652069-7");
        pageTracker._trackPageview();
    } catch(err) {}
</script>
<!-- End of Google Analytics Code -->