		<br style="clear: both;" />
	</div>
	<!-- end #page -->

	<div id="footer">
		<p>
			<?php echo "KuBlog"; //bloginfo('name'); ?> is proudly powered by <a href="http://kumbiaphp.com/">KumbiaPHP Framework</a>
			&nbsp;&bull;&nbsp;
			Design by <a href="http://www.freewpthemes.net/">Free WordPress Themes</a>
			&nbsp;&bull;&nbsp;
			<a href="<?php echo "#"; //bloginfo('rss2_url'); ?>">Entries (RSS)</a>
			&nbsp;&bull;&nbsp;
			<a href="<?php echo "#"; //bloginfo('comments_rss2_url'); ?>">Comments (RSS)</a>
		</p>
	</div>
	<!-- end #footer -->
</body>
</html>



