<?php
/**
 * Partials que muestra información del usuario autenticado
 */
Load::lib('auth');
?>

<div id='head-user'>
    <h1>KuBlog</h1><div id='title2'>Sistema de blog potenciado por KumbiaPHP</div>
    <div class='alignright'>
        <p id='info-user'>
            <span class='info-user'>Hola <?php echo Auth::get('nombre');//echo Auth::get('login') ?></span>
            <?php echo Html::link('admin/usuario/cambiar_clave/', 'Cambiar Clave', "title='Cambio de Clave'"); ?>
            <?php echo Html::link('logout/', 'Salir', "title='Salir del Sistema'") ?>
        </p>
    </div>
</div>