<script type="text/javascript">
    var headID = document.getElementsByTagName("head")[0];
    var cssNode = document.createElement('link');
    cssNode.type = 'text/css';
    cssNode.rel = 'stylesheet';
    cssNode.href = '<?php echo PUBLIC_PATH ?>css/menu/dropdown.css';
    cssNode.media = 'all';
    headID.appendChild(cssNode);

    var cssNode = document.createElement('link');
    cssNode.type = 'text/css';
    cssNode.rel = 'stylesheet';
    cssNode.href = "<?php echo PUBLIC_PATH ?>css/menu/default.advanced.css";
    cssNode.media = 'all';
    headID.appendChild(cssNode);
</script>

<ul class="dropdown dropdown-horizontal">
    <?php foreach (Load::model('controlador')->getMenu(Auth::get('perfil_id')) as $item): ?>
        <li>
            <a href='#' title="<?php echo $item->Menu()->titulo ?>"><?php echo $item->Menu()->nombre ?></a>
            <ul>
            <?php foreach (Load::model('controlador')->getSubMenu(Auth::get('perfil_id'), $item->Menu()->id) as $controlador): ?>
            <?php if ($controlador->url == 'null') {
 ?>
                    <li class="empty"><?php echo $controlador->nombre ?></li>
<?php } else { ?>
                    <li><?php echo Html::link("$controlador->url/", $controlador->nombre) ?></li>
            <?php } ?>
<?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
<?php if (Auth::get('perfil_id') == 1) { ?>
                    <li>
                        <a title="Menu Administrativo" href="#">Admin</a>
                        <ul>
                            <li class="empty">Controladores</li>
                            <li><?php echo Html::link('admin/controlador/', 'Listar controladores') ?></li>
                            <li><?php echo Html::link('admin/controlador/create/', 'Crear controlador') ?></li>
                            <li class="empty">Menus</li>
                            <li><?php echo Html::link('admin/menu/', 'Listar menu') ?></li>
                            <li><?php echo Html::link('admin/menu/create/', 'Crear menú') ?></li>
                        </ul>
                    </li>
<?php } ?>
                        <li class="right">
<?php echo Html::link('', 'Ver sitio', 'target="_blank"') ?>
                    </li>
                    <li class="right">
<?php echo Html::link('logout/', 'Salir') ?>
    </li>
</ul>