<h3>Nueva Galería de flicker</h3>
<div class="form">
    <?php View::content(); ?>
    <?php echo Form::open('admin/flickr_set/create/') ?>        
    <div class="row">
        <label for="flickr_set_id">Galería Id</label>
        <?php echo Form::text('flickr_set.set_id', "size='40'") ?>
    </div>
    <div class="row">
        <label for="flickr_set_titulo">Título</label>
        <?php echo Form::text('flickr_set.titulo', "size='40'") ?>
    </div>
     <div class="row">
        <label for="flickr_set_descripcion">Descripción</label>
        <?php echo Form::text('flickr_set.descripcion_corta', "size='40'") ?>
    </div>
    <div class="row">
        <label for="flickr_set_contenido">Contenido</label>
        <?php echo Form::textarea('flickr_set.contenido', "style='width:100%'")?>
    </div>
    <div class="row">
        <label for="flickr_set_slug">Slug</label>
        <?php echo Form::text('flickr_set.slug', "size='40'") ?>
    </div>
    <div class="row">
        <label for="flickr_set_status">Estado</label>
        <?php echo Form::select('flickr_set.estado',
        array('0' => 'Borrador', '1' => 'Publicado', '2' => 'Archivado')) ?>
    </div>
    
    <div class="row action">
        <?php View::partial('widgets/tinymce') ?>
        <?php echo Form::submit('Enviar') ?>
    </div>
    <?php echo Form::close() ?>
</div>