<h3>Lista de Flickr</h3>
<div class="content">
    <?php View::content(); ?>
    <table id="minimalist">
        <thead><tr>
                <th>Nombre</th>
                          
                <th colspan="2" class='action'>Acciones</th>
            </tr></thead>
        <tbody>
            <? foreach($listPosts->items as $item):?>
            <tr>                
                <td><?php eh($item->titulo) ?></td>
                
                    <?php if($item->estado == FlickrSet::STATUS_PUBLISHED): ?>
                <td><img alt="Artículo Publicado" src="/img/public.png" title="Artículo Publicado" /></td>
                    <?php else:?>
                <td><img alt="Candidato Artículo Bueno" src="/img/candidaro-articulo-bueno.png" title="Candidato Artículo Bueno" /></td>
                    <?php endif;?>
                <td><?php echo Html::link("admin/flickr_set/edit/$item->id/", Html::img('edit.png'), "title='Editar Registro' class='edit'")?></td>
                <td><?php echo js::link("admin/flickr_set/del/$item->id/", '<img alt="Borra" src="/img/delete.png" title="Borrar Noticia" />', '¿Esta seguro que desea eliminar este registro?', 'del') ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <?php View::partial('paginators/classic', false, array('page' => $listPosts ,'url' => 'admin/flickr_set/index')); ?>
</div>
