<?php
/**
 * Formulario realizado con autocarga de objeto
 * model.campo
 *
 * KumbiaPHP implementa la autocarga de objeto la cual siguiendo la convencion model.field
 * En este caso el model es "controlador" si vamos a la BD se vera que existe una tabla
 * llamada "controlador" y field (campo) serán los campos de esa tabla.
 *
 * Veamos la estructuta de tabla controlador:
 * CREATE TABLE controlador
 * (
 *   id           int            unique not null auto_increment,
 *   nombre       varchar(100),
 *   url          varchar(100)   not null,
 *   status       char(1)        not null,
 *   perfiles_id  int            not null,
 *   menu_id      int            not null,
 *   primary key(id),
 *   foreign key(perfiles_id) references perfiles(id),
 *   foreign key(menu_id) references menu(id)
 * )
 * TYPE = InnoDB;
 *
 * En concordancia con los fields (campos) de la tabla "controlador" se indica el comportamiento de la autocarga de objeto
 * para que el controller no tener que recoger cada uno de los valores enviado por POST.
 *
 * Para este caso haremos en los helpers:
 * text_field_tag(array('controlador.url'))
 *
 * Automáticamente cuando ese valor vaya al action menu/create KumbiaPHP interpreta que existe una tabla "controlador" con un campo "url"
 * y si vemos la estructura de la tabla es asi.
 *
 * Ahora debes ir al método create del controller menu, para que observes como se hace esta asociación.
 */
?>
<h3>Nuevo Controlador</h3>
<?php View::content(); ?>
<?php echo Form::open() ?>
<div class="form">
    <div class="row">
        <label for="controlador_perfil_id">Perfil</label>
        <?php
        echo Form::dbSelect('controlador.perfil_id',
                $perfiles, 'nombre',
                'Seleccione...')
        ?>
    </div>

    <div class="row">
        <label for='controlador_menu_id'>Menú</label>
        <?php
        echo Form::dbSelect('controlador.menu_id',
                $menu, 'nombre',
                'Seleccione...')
        ?>
    </div>

    <div class="row">
        <label for='controlador_url'>URL</label>
<?php echo Form::text('controlador.url') ?>
        <div class='hint'>Ej: module/controller/action</div>
    </div>

    <div class="row">
        <label for='controlador_nombre'>Nombre a Mostrar</label>
<?php echo Form::text('controlador.nombre') ?>
    </div>

    <div class="row">
        <label for='controlador_status'>Estado</label>
<?php echo Form::select('controlador.status',
                array('A' => 'Activo', 'D' => 'Desactivado')) ?>
    </div>

    <div class="row action">
<?php echo Form::submit('Enviar') ?>
            </div>
        </div>
<?php echo Form::close(); ?>
