<div id='posts'>
	<h2>¿Que es TEMIGA?</h2>
	<p>Sabes que es <strong>TEMIGA</strong>..? muchas personas hacen esta pregunta y muchos no creen que un 
	grupo de tecnologías pueda tener un nombre como este y si para quienes no lo creen 
	<strong>TEMIGA = residuo pastoso de color blanquecino que se forma del resto de la orina en el 
	prepucio de los hombres desaseados, normalmente con un mal olor</strong>, 
	TEMIGOSO = hombre que por su estado de desaseo tiene este material en su genital y 
	por ende emana un cierto mal olor a orine descompuesto ;-)</p>
	
	<p>Este es un klan que con el pasar del tiempo se ha hecho más famoso y a su 
	vez sus integrantes más PowerUser, a pesar de sus responsabilidades en el ámbito 
	laboral y personal siempre se han mantenido activos en el site aportando ideas 
	y comentarios acerca de tech, gamer's, entre otros temas de interés tecnológicos del Klan, 
	si deseas conocer más o ser integrante de este grupo de panas te invitamos a que visites nuestro 
	<a title="Foro del Klan Temiga" href="http://www.temiga.org/index.php?option=com_smf&Itemid=49" target="_blank">Foro</a> y 
	<a title="Sitio oficial del Klan TEMIGA" href="http://www.temiga.org" target="_blank">Portal</a></p>
</div>