<?php

View::content(); 
Load::lib('helpers');

?>
<div class="posts">
    <?php foreach ($articulos->items as $articulo): ?>
    <div class="post">        
        <h2 class="title"><?php echo Html::link("articulo/$articulo->slug/", $articulo->titulo, "title='$articulo->titulo'") ?></h2>
        <p class="info">
            Enviado por <?php echo $articulo->getUsuario()->nombre; ?> el <?php echo strftime("%e de %B del %Y", strtotime($articulo->creado_at));  ?>
        </p>
        <div class="entry">
                <?php echo $articulo->contenido;?>
        </div>
        <p class="postmetadata">Etiquetas: <?php echo Helpers::getTags($articulo->id) ?></p>
        <?php echo Html::link("nuevo_comentario/$articulo->slug/", 'Deja tu comentario') ?>
    </div>
    <?php endforeach; ?>
    <div class="space"></div>
    <div class="navigation">
        <div class="alignleft">
            <?php if($articulos->prev) echo Html::link("page/$articulos->prev/", '<span class="older">Noticias Recientes</span>'); ?></div>
        <div class="alignright">
            <?php if($articulos->next) echo Html::link("page/$articulos->next/", '<span class="newer">Noticias Anteriores</span>'); ?></div>
    </div>
</div><!-- end posts -->
