<?php if ($articulo != NULL) : ?>
		<div class="post" id="post-<?php echo $articulo->id; ?>">
			<h2 class="title"><?php echo Html::link("articulo/$articulo->slug/", $articulo->titulo, "title='$articulo->titulo'") ?></h2>
			<p class="byline"><small>Por <?php echo $articulo->getUsuario()->nombre; ?> el <?php echo strftime("%e de %B del %Y", strtotime($articulo->creado_at));  ?></small></p>
			<div class="entry">
				<?php echo $articulo->contenido; ?>
			</div>
			<div class="meta">
				<p class="tags"><strong>Tags: </strong><?php echo Helpers::etiquetasPorPost($articulo->id, " &bull "); ?></p>
				<p class="links">
					<?php echo "<a href='#'>Editar</a>"; ?>
				</p>
			</div>
			<hr /><br />

			<div id="comments" name="comments">
			    <h3>Dejanos tu Comentario</h3>
				<?php View::Content(); ?>
			    <div class="form">
				<?php echo Form::open("nuevoComentario/$articulo->slug/#comments", 'post') ?>
				<?php echo Form::hidden('comentario.articulo_id', '',$articulo->id) ?>
				<table>
				    <tr>
					<td><label for="comentario_autor">Nombre (*):</label></td>
					<td><?php echo Form::text('comentario.autor')?></td>
				    </tr>
				    <tr>
					<td><label for="comentario_email">Correo (*):</label></td>
					<td><?php echo Form::text('comentario.email')?></td>
				    </tr>
				    <tr>
					<td><label for="comentario_url">Sitio web:</label></td>
					<td><?php echo Form::text('comentario.url')?></td>
				    </tr>
				    <tr>
					<td><label for="comentario_autor">Comentario (*):</label></td>
					<td><?php echo Form::textarea('comentario.comentario',array('cols'=>'57', 'rows'=>'6'))?></td>
				    </tr>
				</table>
				<p>
				    <?php echo Form::submit('Enviar')?>
				</p>
				<?php echo Form::close() ?>
			    </div>
			</div>

			<?php if($numComentarios >= 1): ?>
			<h3>
				<?php echo $numComentarios > 1 ? $numComentarios . ' Comentarios' : 'Un Comentario'; ?>
			</h3>
			<?php endif; ?>

			<?php foreach($comentarios as $comentario): ?>
			<p>
			<div class="comment" id="c<?php echo $comentario->id; ?>">
			    <div class="time">
				    <?php echo strftime("%e de %B del %Y, a las %R", strtotime($comentario->creado_at)); ?>
			    </div>
			    <div class="author"><a href='<?php echo $comentario->url ?>' target="_blank"><?php echo $comentario->autor ?></a> dice:</div>
			    <div class="content"><?php echo $comentario->comentario; ?></div>
			</div>
			</p>
			<?php endforeach; ?>
		</div>

<?php else: ?>
		<h3>Lo lamentamos, no se ha encontrado el art&iacute;culo que buscas.</h3>
<?php endif; ?>
