<?php header('Content-type: application/rss+xml'); ?>
<?php echo '<?xml version="1.0" encoding="UTF-8" ?>' ?>
<rss version="2.0">
    <channel>
        <title>simacel.com</title>
        <description>RSS del portal de simacel.com</description>
        <language>es</language>
        <copyright>simacel.com</copyright>
        <link>http://simacel.com/</link>
        <?php foreach ($lastPost as $post): ?>
            <item>
                <title><?php echo $post->titulo ?></title>
                <link><?php echo 'http://' . $_SERVER['HTTP_HOST'] . "/{$post->ruta()}" ?></link>
                <guid><?php echo 'http://' . $_SERVER['HTTP_HOST'] . "/{$post->ruta()}" ?></guid>
                <description><![CDATA[<?php echo $post->contenido ?>]]></description>
                <author>info@simacel.com</author>
                <pubDate><?php echo date(DATE_RSS, strtotime($post->creado_at)) ?></pubDate>
            </item>
        <? endforeach; ?>
    </channel>
</rss>
