<?php
View::content();
Load::lib('helpers');
?>
<?php
foreach ($articulos->items as $post_tag):
    $articulo = $post_tag->getArticulo();
?>
    <article class="hentry">
        <hgroup>
            <h2 class="entry-title"><?php echo Html::link($articulo->ruta(), $articulo->titulo, "title='$articulo->titulo'") ?></h2>
            <h3>Enviado por <a class="author" href="#"><?php eh($articulo->getUsuario()->nombre); ?></a> el <time><abbr class="updated published" title="<?php echo date(DATE_W3C, strtotime($articulo->fecha_publicacion)) ?>"><?php echo strftime("%e de %B del %Y", strtotime($articulo->creado_at)); ?></abbr></time></h3>
        </hgroup>
        <p class="entry-summary"><?php echo $articulo->resumen; ?></p>
        <footer>
        <?php
        if ($articulo->habilitar_comentarios == 1) {
            echo Html::link("nuevo_comentario/{$articulo->rutaSimple()}", "($articulo->numero_comentarios) Comentarios");
        }
        ?>
    </footer>
    <br /><hr /><br />
</article>    
<?php endforeach; ?>
        <div class="space"></div>
        <div class="navigation">
            <div class="alignleft">
        <?php if ($articulos->prev)
            echo Html::link("page/$articulos->prev/", '<span class="older">Noticias Recientes</span>'); ?></div>
    <div class="alignright">
<?php if ($articulos->next)
            echo Html::link("page/$articulos->next/", '<span class="newer">Noticias Anteriores</span>'); ?></div>
</div>