<?php Load::lib('auth') ?>
<?php Load::lib('helpers'); ?>

<div class="post">
    <?php View::content(); ?>
    <h2 class="title"><?php echo Html::link("articulo/$articulo->slug/", $articulo->titulo, "title='$articulo->titulo'") ?></h2>
    <p class='info'>
        Enviado por <?php echo $articulo->getUsuario()->nombre; ?> el <?php echo strftime("%e de %B del %Y", strtotime($articulo->creado_at));  ?>
    </p>
    <?php echo $articulo->contenido; ?>
    <?php if(Auth::is_valid()): ?>
      <div class="nav">
            <?php echo Html::link("admin/articulo/edit/$articulo->id/", 'Actualizar'); ?>
      </div>
    <?php endif; ?>
    <?php View::partial('widgets/socialbar', false, array('url'=>"articulo/$articulo->slug/", 'titulo'=>$articulo->titulo)) ?>
    <p class="postmetadata">Etiquetas: <?php echo Helpers::getTags($articulo->id) ?></p>
</div>