<script type="text/javascript">
    var RecaptchaOptions = {
        lang : 'es'
    };
</script>

<div id="comments">
    <h3>Dejanos tu Comentario</h3>
    <div class="form">
        <?php echo Form::open("nuevo_comentario/$ruta", 'post') ?>
        <?php echo Form::hidden('comentario.articulo_id', '',$articulo_id) ?>
        <table>
            <tr>
                <td><label for="comentario_autor">Nombre (*):</label></td>
                <td><?php echo Form::text('comentario.autor')?></td>
            </tr>
            <tr>
                <td><label for="comentario_email">Correo (*):</label></td>
                <td><?php echo Form::text('comentario.email')?></td>
            </tr>
            <tr>
                <td><label for="comentario_url">Sitio web:</label></td>
                <td><?php echo Form::text('comentario.url')?></td>
            </tr>
            <tr>
                <td><label for="comentario_autor">Comentario (*):</label></td>
                <td><?php echo Form::textarea('comentario.comentario',array('cols'=>'57', 'rows'=>'6'))?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $captcha ?></td>
            </tr>
        </table>
        <p>
            <?php echo Form::submit('Enviar')?>
        </p>
        <?php echo Form::close() ?>
    </div>
</div>