<?php if ($countComment >= 1): ?>
    <h3>
    <?php echo $countComment > 1 ? $countComment . ' Comentarios' : 'Un Comentario'; ?>
</h3>
<?php endif; ?>

<?php foreach ($comentarios as $comment): ?>

        <div class="comment" id="c<?php echo $comment->id; ?>">
            <div class="content">
                <strong>
                    <a name="<?php echo strtotime($comment->creado_at) ?>"></a><a href='<?php echo $comment->url ?>' title="<?php echo $comment->autor; ?>"><?php echo $comment->autor; ?></a>
                </strong>
        <?php echo $comment->comentario; ?>
    </div>
    <div class="time">
        <?php echo strftime("%e de %B del %Y, a las %R", strtotime($comment->creado_at)); ?>
    </div>
</div>
<?php endforeach; ?>