<ul>
	<li>
        <h2>Enlaces</h2>
		<ul>
			<li><a target="_blank" href='http://www.temiga.org/' title='Temiga'>Temiga</a></li>
			<li><a target="_blank" href='http://www.kumbiaphp.com/' title='KumbiaPHP Framework'>KumbiaPHP Framework</a></li>
			<li><a target="_blank" href='http://www.desarrollaphp.com/' title='Blog sobre temas de PHP'>Desarrolla con PHP</a></li>
			<li><a target="_blank" href='http://www.cl-radio.com/' title='Radio por Internet en Venezuela'>CL-Radio.com</a></li>
			<li><a target="_blank" href='http://canaima.softwarelibre.gob.ve/cms' title='Sistema Operativo Venezolano Canaima'>Canaima S.O</a></li>
    	</ul>
	</li>
	<li>
        <h2>Blog Temiga's</h2>
		<ul>
			<li><a target="_blank" href='http://athila.temiga.org/' title='Blog de AThilA'>AThilA</a></li>
			<li><a target="_blank" href='http://virussx.temiga.org/' title='Blog de Virussx'>Virussx</a></li>
			<li><a target="_blank" href='http://kuro.temiga.org/' title='Blog de Kuro'>Kuro</a></li>
			<li><a target="_blank" href='http://saintdirty.temiga.org/' title='Blog de SaintDirty'>SaintDirty</a></li>
			<li><a target="_blank" href='http://vairok.temiga.org/' title='Blog de Vairok'>Vairok</a></li>
    	</ul>
	</li>
</ul>