<?php
/**
 * Visualizar feed
 *
 * @param string $nombre Nombre
 * @param string $url URL completa del feed
 * @return html
 */
?>	
<ul><li>
<?php if ($feed = simplexml_load_file($url)){ ?>
    <h2><?php echo $nombre ?></h2>
    <ul>
        <? foreach ($feed->channel->item as $item) : ?>
        <li><a href="<?php echo $item->link?>" target="_blank" title="<?php echo $item->description?>"><?php echo $item->title ?></a></li>
        <? endforeach?>
    </ul>
<?php }?>
</li></ul>