<style>
.sociable { margin: 16px 0; }

.sociable ul {
	display: inline;
	margin: 0 !important;
	padding: 0 !important;
}
.sociable ul li {
	background: none;
	display: inline !important;
	list-style-type: none;
	margin: 0;
	padding: 1px;
}

.sociable-hovers {
	opacity: .4;
	-moz-opacity: .4;
	filter: alpha(opacity=40);
}
.sociable-hovers:hover {
	opacity: 1;
	-moz-opacity: 1;
	filter: alpha(opacity=100);
}
</style>

<div class="sociable">
<p>¿Te gustó este post? ¡Compártelo!</p>
<ul>
	<?php $url = 'http://'.$_SERVER['SERVER_NAME'].Router::get('route') ?>
	<li><a rel="nofollow" target="_blank" href="http://bitacoras.com/anotaciones/<?php echo $url ?>" title="Bitacoras.com"><img src="/img/sociable/bitacoras.png" title="Bitacoras.com" alt="Bitacoras.com" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://ocio.fresqui.com/post?url=<?=$url?>&amp;title=%E2%80%9C<?=$titulo?>%E2%80%9D"><img alt="Fresqui" src="/img/sociable/fresqui.gif" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://twitter.com/home?status=<?php echo $url ?>" title="TwitThis"><img src="/img/sociable/twitter.png" title="TwitThis" alt="TwitThis" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://www.facebook.com/share.php?u=<?php echo $url ?>&amp;t=<?php echo $titulo ?>" title="Facebook"><img src="/img/sociable/facebook.png" title="Facebook" alt="Facebook" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://meneame.net/submit.php?url=<?php echo $url ?>" title="Meneame"><img src="/img/sociable/meneame.png" title="Meneame" alt="Meneame" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://www.google.com/bookmarks/mark?op=edit&amp;bkmk=<?php echo $url?>&amp;title=%E2%80%9C<?=$titulo?>%E2%80%9D"><img src="/img/sociable/googlebookmark.png" title="Google Bookmarks" alt="Google Bookmarks" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://delicious.com/post?url=<?=$url?>&amp;title=%E2%80%9C<?=$titulo?>%E2%80%9D"><img src="/img/sociable/delicious.png" title="del.icio.us" alt="del.icio.us" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="https://favorites.live.com/quickadd.aspx?marklet=1&amp;url=<?php echo $url?>" title="Windows Live"><img src="/img/sociable/live.png" title="Live" alt="Live" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://technorati.com/faves?add=<?php echo $url?>" title="Technorati"><img src="/img/sociable/technorati.png" title="Technorati" alt="Technorati" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://www.wikio.com/vote?url=<?php echo $url?>" title="Wikio"><img src="/img/sociable/wikio.png" title="Wikio" alt="Wikio" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://digg.com/submit?phase=2&amp;url=<?=$url?>&amp;title=%E2%80%9C<?=$titulo?>%E2%80%9D" title="Digg"><img alt="Digg" src="/img/sociable/digg.png" class="sociable-hovers" /></a></li>
	<li><a rel="nofollow" target="_blank" href="http://myweb2.search.yahoo.com/myresults/bookmarklet?u=<?=$url?>&amp;t=%E2%80%9C<?=$titulo?>%E2%80%9D" title="Yahoo My Web"><img alt="Yahoo My Web" src="/img/sociable/yahoomyweb.png" class="sociable-hovers" /></a></li>
</ul>
</div>
