<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>javascript/tinymce/jscripts/tiny_mce/tiny_mce.js"></script> 
<script type="text/javascript"><!--
    tinyMCE.init({
        mode : "textareas",
        theme : "advanced",
        language : "en",
        readonly : false,
        plugins : "spellchecker,pagebreak,style,layer,advimage,advlink,emotions,media,searchreplace,fullscreen,noneditable,visualchars",

        // Theme options
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,|,formatselect,fontsizeselect,|,cut,copy,paste",
        theme_advanced_buttons2 : "search,replace,|,bullist,numlist,|,blockquote,|,undo,redo,|,link,unlink,anchor,image,code,|,forecolor,backcolor,|,hr,removeformat,visualaid,|,charmap,emotions,iespell,media,|,fullscreen,blockquote,pagebreak",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        //extended_valid_elements : "a[name|href|target|title],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|name],hr[class|width|size|noshade],span[class]",
        theme_advanced_resizing : true,
        entity_encoding : "raw",
        relative_urls : false,
        remove_script_host : false

        //content_css : "/content.css"
    });
</script> 