<script type="text/javascript" src="<?php echo PUBLIC_PATH ?>javascript/tinymce/jscripts/tiny_mce/tiny_mce.js"></script>
<script type="text/javascript"><!--
    tinyMCE.init({
        file_browser_callback: 'openKCFinder',
        // General options
        mode : "textareas",
        theme : "advanced",
        language : "en",
        readonly : false,
        plugins : "safari,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,imagemanager,filemanager",

        // Theme options
        theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,|,formatselect,fontsizeselect,|,cut,copy,paste",
        theme_advanced_buttons2 : "search,replace,|,bullist,numlist,|,blockquote,|,undo,redo,|,link,unlink,anchor,image,code,|,forecolor,backcolor,|,hr,removeformat,visualaid,|,charmap,emotions,iespell,media,|,fullscreen,blockquote,pagebreak",
        theme_advanced_buttons3 : "",
        theme_advanced_toolbar_location : "top",
        theme_advanced_toolbar_align : "left",
        theme_advanced_statusbar_location : "bottom",
        //extended_valid_elements : "a[name|href|target|title],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|name],hr[class|width|size|noshade],span[class]",
        theme_advanced_resizing : true,
        entity_encoding : "raw",
        relative_urls : false,
        remove_script_host : false

    });

    function openKCFinder(field_name, url, type, win) {
        tinyMCE.activeEditor.windowManager.open({
            file: '<?php echo PUBLIC_PATH ?>javascript/kcfinder/browse.php?opener=tinymce&dir=/img/upload/&type=' + type,
            title: 'KCFinder',
            width: 700,
            height: 500,
            resizable: "yes",
            inline: true,
            close_previous: "no",
            popup_css: false
        }, {
            window: win,
            input: field_name
        });
        return false;
    }
</script>