<script type="text/javascript">
    var headID = document.getElementsByTagName("head")[0];         
    var cssNode = document.createElement('link');
    cssNode.type = 'text/css';
    cssNode.rel = 'stylesheet';
    cssNode.href = '<?php echo URL_PATH ?>css/jquery.lightbox-0.5.css';
    cssNode.media = 'screen';
    headID.appendChild(cssNode);
</script>  
<?php
    echo javascript_include_tag('jquery/jquery-1.3.2.min');
    echo javascript_include_tag('jquery/jquery.lightbox-0.5');
?>
   	<style type="text/css">
	/* jQuery lightBox plugin - Gallery style */
	div#gallery {
		width: 190px;
	}
	div#gallery ul li ul { list-style: none; }
	div#gallery ul li ul li { background: none; display: inline; list-style-position: inside; padding-left: 13px;}
	div#gallery ul li ul li a img {
		border: 2px solid #3e3e3e;
	}
	div#gallery ul li ul li a:hover img {
		border: 2px solid #fff;
		color: #fff;
	}
	div#gallery ul li ul li a:hover { color: #fff; }
	</style>
<?php
/**
 * Visualizar feed
 *
 * @param string $nombre Nombre
 * @param string $url URL completa del feed
 * @return html
 */
$url = 'http://api.flickr.com/services/rest/?method=flickr.people.getPublicPhotos&api_key=31d2d8c82864148c800ba8148fbbef29&user_id=16933812@N08&per_page=4';
$result = simplexml_load_file($url);
?>
<div id="gallery"><ul><li>
<? if ($result){ ?>
    <h2><?php echo $name ?></h2>
    <ul>
    <? foreach ($result->photos->photo as $r): ?>
        <li>
            <a href="<?php echo "http://farm".$r['farm'].".static.flickr.com/".$r['server']."/".$r['id']."_".$r['secret'].".jpg" ?>">
                    <img src="<?php echo "http://farm".$r['farm'].".static.flickr.com/".$r['server']."/".$r['id']."_".$r['secret']."_s.jpg" ?>"
                         title="<?php echo $r['title']?>" alt="<?php echo $r['title']?>" />
            </a>
        </li>
        <? endforeach?>
    </ul>
<?php } ?>
</li></ul></div>
    <script type="text/javascript">
    $(function() {
        $('#gallery a').lightBox();
    });
    </script>