<div class="post">
    <?php View::content(); ?>
    <h2 class="title"><?php echo Html::link("galeria/$galeria->slug/", $galeria->titulo, "title='$galeria->titulo'") ?></h2>
    <p class='info'>
        Enviado el <?php echo strftime("%e de %B del %Y", strtotime($galeria->creado_at));  ?>
    </p>
    <div align="center">
        <iframe align="center" src="http://www.flickr.com/slideShow/index.gne?group_id=&user_id=50030787@N04&set_id=<?php echo $galeria->set_id?>&text=" frameBorder="0" width="500" height="500" scrolling="no"></iframe>
        <br/>
    </div>
    <p>
        <?php echo $galeria->contenido ?>
    </p>
    <?php if(Auth::is_valid()): ?>
    <div class="nav">
            <?php echo Html::link("admin/flickr_set/edit/$galeria->id/", 'Actualizar'); ?>
    </div>
    <?php endif; ?>
    <?php View::partial('widgets/socialbar', false, array('url'=>"galeria/$galeria->slug/", 'titulo'=>$galeria->titulo)) ?>
</div>